[workspace]
resolver = "2"
members = [
        "redfish-axum",
        "redfish-core",
        "redfish-models",
        "redfish-macros",
        "seuss",
        "examples/simple",
        "redfish-codegen",
]
