[package]
name = "into-redfish-message"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = "1.0.109"
lazy_static = "1.4.0"
regex = "1.7.1"
