[package]
name = "seuss-auth-pam"
version = "0.1.0"
edition = "2021"

[dependencies]
seuss = { version = "0.1.0", path = "../seuss" }
redfish-codegen = { version = "0.2.0", path = "../redfish-codegen" }
pam = "0.7.0"
users = "0.11.0"
