// Generated by redfish-codegen. Do not modify.
// Author: Ethan D. Twardy <ethan.twardy@gmail.com>
//
// Copyright 2023, Ethan Twardy. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the \"License\");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an \"AS IS\" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#[cfg(feature = "api")]
pub mod api;
pub mod models;
pub mod registries;
#[cfg(feature = "routing")]
pub mod routing;

/// The version of the Redfish Schema Specification provided by this crate.
pub const REDFISH_VERSION: &'static str = "2022.3";
