// Generated by redfish-codegen. Do not modify.

pub mod base;
pub mod composition;
pub mod environmental;
pub mod ethernet_fabric;
pub mod fabric;
pub mod heartbeat_event;
pub mod job_event;
pub mod license;
pub mod log_service;
pub mod network_device;
pub mod platform;
pub mod power;
pub mod resource_event;
pub mod sensor_event;
pub mod storage_device;
pub mod task_event;
pub mod update;
